on:
  push:
    branches:
      - master

jobs:
  deploy-gh-page:
    name: deploy-gh-page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir ./example/clever-date
      - run: npm install
      - run: npm run build
      - run: cp -r ./dist/* ./example/clever-date/
      - run: sed -i 's/\.\.\/dist/clever-date/g' ./example/index.html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.PUBLISH_DIST_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./example
